max_bag_size_gb: 20
max_cache_size_mb: 1000
topics:
  # Teensy sensor state and logs
  - /teensy/sensor
  - /teensy/log

  # Flic button pressed times
  - /flic/button_pressed_time

  # Optitrack markers and rigid bodies, and their republished visualization messages
  - /markers
  - /markers_viz
  - /predicted_markers_viz
  - /rigid_bodies
  - /rigid_bodies_viz

  # Eyelink samples and predicted gaze markers
  - /eyelink/sample
  - /eyelink/sample_array
  - /predicted_markers

  # Flir camera images and metadata
  # We use the base image topic name as opposed to the one suffixed by the image
  # transport (i.e. /image_topic vs /image_topic/compressed) since the rosbag
  # recorded seems to only record the image topics that way.
  - /cam_sync/left_front_top_cam/image_raw
  - /cam_sync/left_front_top_cam/camera_info
  - /cam_sync/left_front_top_cam/meta

  - /cam_sync/left_back_top_cam/image_raw
  - /cam_sync/left_back_top_cam/camera_info
  - /cam_sync/left_back_top_cam/meta

  - /cam_sync/left_bottom_cam/image_raw
  - /cam_sync/left_bottom_cam/camera_info
  - /cam_sync/left_bottom_cam/meta

  - /cam_sync/right_front_top_cam/image_raw
  - /cam_sync/right_front_top_cam/camera_info
  - /cam_sync/right_front_top_cam/meta

  - /cam_sync/right_back_top_cam/image_raw
  - /cam_sync/right_back_top_cam/camera_info
  - /cam_sync/right_back_top_cam/meta

  - /cam_sync/right_bottom_cam/image_raw
  - /cam_sync/right_bottom_cam/camera_info
  - /cam_sync/right_bottom_cam/meta

  # Robot joint states (covers both robots)
  - /joint_states
  - /dynamic_joint_states

  # Robot end effector torque
  - /force_torque_sensor_broadcaster/wrench
  - /force_torque_sensor_broadcaster/wrench_filtered

  # ROS out
  - /rosout
services:
  - /teensy/ping
  - /teensy/set_arm_lock
  - /teensy/set_smartglass
  - /teensy/set_reward
  - /teensy/set_solenoid
