common:
  camera_type: blackfly_s
  debug: false
  compute_brightness: false
  adjust_timestamp: true
  dump_node_map: false
  # set parameters defined in blackfly_s.yaml
  exposure_auto: "Off"
  gain_auto: Continuous
  frame_rate_enable: true
  exposure_time: 4000
  frame_rate: 120.0
  trigger_mode: "Off"
  # pixel_format: BayerRG8
  # exposure_auto: Continuous
  # to use a user set, do this:
  # user_set_selector: UserSet0
  # user_set_load: Yes
  # to reduce the sensor width and shift the crop
  # image_width: 1408
  # image_height: 1080
  # offset_x: 16
  # offset_y: 0
  # binning_x: 1
  # binning_y: 1
  # connect_while_subscribed: true
  # reverse_x: true
  # reverse_y: true
  # frame_rate_auto: "Off"
  buffer_queue_size: 4
  chunk_mode_active: true
  chunk_selector_frame_id: FrameID
  chunk_enable_frame_id: true
  chunk_selector_exposure_time: ExposureTime
  chunk_enable_exposure_time: true
  chunk_selector_gain: Gain
  chunk_enable_gain: true
  chunk_selector_timestamp: Timestamp
  chunk_enable_timestamp: true
  # stream_buffer_handling_mode: NewestFirst
  # multicast_monitor_mode: false
cameras:
  - name: cam1
    serial_number: "22442796"
  - name: cam2
    serial_number: "23240397"
  - name: cam3
    serial_number: "23240393"
  - name: cam4
    serial_number: "22157020"
  - name: cam5
    serial_number: "23240395"
