repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: debug-statements
      - id: name-tests-test
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.14
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        exclude: pio_compiledb.py
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.11.0.1
  #   hooks:
  #     - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
        args: ["-fallback-style=none"]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
        args:
          [--line-width  220, --disabled-codes=C0307, --suppress-decorations]
