name: tabletop

services:
  autoheal:
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-tabletop
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  novnc:
    build:
      context: ./docker/novnc
      pull: true
    networks:
      tabletop_net:
        ipv4_address: 192.168.12.100
    hostname: novnc
    ports:
      - 8080:8080
    environment:
      - DISPLAY_WIDTH=${TT_DISPLAY_WIDTH:-1280}
      - DISPLAY_HEIGHT=${TT_DISPLAY_HEIGHT:-824}
      - WINDOW_MANAGER=dwm
    depends_on:
      - autoheal
    labels:
      autoheal-tabletop: true

  ursim:
    image: universalrobots/ursim_e-series:latest
    pull_policy: always
    networks:
      tabletop_net:
        ipv4_address: 192.168.12.20
    hostname: ursim
    restart: unless-stopped
    volumes:
      - ./ur_robot/urcaps:/urcaps
      - ./ur_robot/programs:/ursim/programs
      - ./docker/ursim/entrypoint.sh:/entrypoint.sh
    environment:
      - ROBOT_MODEL=ur5e
      - DISPLAY=novnc:0.0
    init: true
    entrypoint: ["/entrypoint.sh"]
    depends_on:
      novnc:
        condition: service_healthy

  flic:
    image: ubuntu:latest
    pull_policy: always
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./docker/flic:/app
    environment:
      - HCI_DEV=hci0
      - BD_ADDR=c8:c6:ac:df:da:c2
      - PORT=5551
      - SERVER_ADDR=0.0.0.0
    init: true
    command: /app/entrypoint.sh
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
      start_interval: 2s
    depends_on:
      - autoheal
    labels:
      autoheal-tabletop: true

  server-base:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      target: base
      pull: true
      args:
        - ROS_DISTRO=jazzy
        - USER=$TT_USER
        - UID=$TT_UID
        - GID=$TT_GID
        - USE_NVIDIA=$TT_USE_NVIDIA
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./
        target: /home/$TT_USER/tabletop
        consistency: cached
      - /home/$TT_USER/tabletop/.venv
    working_dir: /home/$TT_USER/tabletop
    init: true
    command: sleep infinity

  optitrack:
    extends: server-base
    network_mode: host
    command: bash -c "source \$TABLETOP_DIR/setup.bash && ros2 launch mocap4r2_optitrack_driver optitrack2.launch.py"

  server:
    extends: server-base
    runtime: $TT_CONTAINER_RUNTIME
    networks:
      tabletop_net:
        ipv4_address: 192.168.12.10
    hostname: server
    ports:
      - 50001:50001
      - 50002:50002
      - 50003:50003
      - 50004:50004
    # Uncomment the following section if you plan on connecting a teensy after starting the container
    # device_cgroup_rules:
    #   - c 161:* rmw
    # Uncomment the following section if a teensy is connected before starting the container
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DISPLAY=novnc:0.0
      # - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=$TT_NVIDIA_VISIBLE_DEVICES
      - NVIDIA_DRIVER_CAPABILITIES=$TT_NVIDIA_DRIVER_CAPABILITIES
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      # - PULSE_COOKIE=/tmp/pulseaudio.cookie
    volumes:
      - ${TT_PULSE_SERVER_HOST:-/dev/null}:/tmp/pulseaudio.socket
      - ${TT_PULSE_COOKIE_HOST:-/dev/null}:/home/$TT_USER/.config/pulse/cookie
      # - ~/.config/pulse:/home/$TT_USER/.config/pulse:ro
    depends_on:
      novnc:
        condition: service_healthy

  server-dev:
    extends: server
    build:
      target: dev
    # Uncomment the following section if you plan on uploading code to the teensy from the dev container
    privileged: true
    volumes:
      - /dev:/dev
      - ~/.vimrc:/home/$TT_USER/.vimrc
      - ~/.config/nvim:/home/$TT_USER/.config/nvim
      - ~/.config/starship.toml:/home/$TT_USER/.config/starship.toml
    environment:
      - SHELL=/bin/bash

networks:
  tabletop_net:
    name: tabletop_net
    attachable: true
    driver: bridge
    # driver_opts:
    #   com.docker.network.bridge.gateway_mode_ipv4: routed
    ipam:
      config:
        - subnet: 192.168.12.0/24
