tasks:
  - class: ForagingTask
    kwargs:
      fixation_timeout: 5.0
      fixation_duration: 0.5
      stimulus_duration: 2.0
      delay_duration: 2.0
      response_timeout: 20.0
      reward_duration: 0.1
      reveal_duration: 0.5
      trial_generator:
        class: RandomChoice
        kwargs:
          object_ids:
            - simple_object_5
            - simple_object_7
            - simple_object_9
            - simple_object_15
            - simple_object_17
            - simple_object_19
            - simple_object_25
            - simple_object_27
            - simple_object_29
          poses:
            - position: [1.0, 0.4, 0.6]
              rpy: [0.0, 0.2, 0.0]
            - position: [0.9, 0.5, 0.5]
              rpy: [0.0, 0.0, 0.0]
          occlude_prob: 0.0
          num_trials: 1000
