tasks:
  - class: ForagingTask
    kwargs:
      trial_generator:
        class: OrderedChoice
        kwargs:
          object_ids:
            - small_object_15
            - small_object_16
            - small_object_17
            - small_object_18
            # - small_object_19
            - small_object_20
            - small_object_21
            # - small_object_22
            - small_object_23
            - small_object_24
            - small_object_25
            - small_object_26
            - small_object_27
            - small_object_28
            - small_object_29
          poses:
            - position: [1.0, 0.4, 0.6]
              rpy: [0.0, 0.2, -1.5707]
            - position: [0.9, 0.4, 0.6]
              rpy: [0.0, -0.3, -1.5707]
          arms:
            - left
            - right
            - both
          occlude:
            - false
          num_trials: 100000
      stimulus_duration: 0.5
      delay_duration: 0.5
      response_timeout: 2.5
      reward_duration: 2.0
      reveal_duration: 0.5
      reward_sound: true
      sound_kwargs:
        duration: 0.5
