tasks:
  - class: SmoothPursuitTask
    kwargs:
      motion_type: spiral
      motion_kwargs:
        center_pose:
          position: [1.0525, 0.45, 0.45]
          rpy: [1.5707, 1.5707, 0.0]
        radius: 0.05
        length: 0.2
        num_revolutions: 5
        num_segments: 800
      num_repetitions: 3
      object_id: small_object_30
      velocity_scaling_factor: 0.1
