tasks:
  - class: SmoothPursuitTask
    kwargs:
      motion_type: random
      motion_kwargs:
        start_pose_kwargs:
          position: [0.9525, 0.5, 0.7]
          rpy: [1.5707, 1.5707, 0.0]
        min_x: 0.7525
        max_x: 1.1525
        min_y: 0.4
        max_y: 0.6
        min_z: 0.6
        max_z: 0.8
        num_waypoints: 100
      num_repetitions: 3
      object_id: small_object_30
      velocity_scaling_factor: 0.1
