tasks:
  - class: SmoothPursuitTask
    kwargs:
      center_pose:
        position: [0.9525, 0.5, 0.7]
        rpy: [1.5707, 1.5707, 0.0]
      radius: 0.1
      length: 0.2
      num_revolutions: 10
      num_segments: 200
      num_cycles: 20
      reward_period: 1.0
      reward_duration: 0.1
      execute_request_params:
        validate_trajectory: false
        apply_totg: true
        apply_smoothing: true
        velocity_scaling_factor: 0.5
        acceleration_scaling_factor: 0.5
        path_tolerance: 0.01
        resample_dt: 0.1
        min_angle_change: 0.001
        mitigate_overshoot: false
        overshoot_threshold: 0.002
