# These limits are used by MoveIt and augment/override the definitions in ur_description.

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
# default_velocity_scaling_factor: 1.0
# default_acceleration_scaling_factor: 1.0

# While the robot does not inherently have any limits on joint accelerations (only on torques),
# MoveIt needs them for time parametrization. They were chosen conservatively to work in most use
# cases. For specific applications, higher values might lead to better execution performance.

joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_velocity_limits: true
    max_velocity: 3.1416
    has_jerk_limits: true
    max_jerk: 5000.0
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_velocity_limits: true
    max_velocity: 3.1416
    has_jerk_limits: true
    max_jerk: 5000.0
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_velocity_limits: true
    max_velocity: 3.1416
    has_jerk_limits: true
    max_jerk: 5000.0
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_velocity_limits: true
    max_velocity: 10.0
    has_jerk_limits: true
    max_jerk: 5000.0
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_velocity_limits: true
    max_velocity: 10.0
    has_jerk_limits: true
    max_jerk: 5000.0
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_velocity_limits: true
    max_velocity: 10.0
    has_jerk_limits: true
    max_jerk: 5000.0
