[env:teensy41]
platform = teensy@5.1.0
board = teensy41
framework = arduino
upload_protocol = teensy-cli
board_microros_transport = serial
board_microros_distro = jazzy
board_microros_user_meta = colcon.meta
extra_scripts = pio_compiledb.py
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
platform_packages =
    platformio/toolchain-gccarmnoneeabi-teensy@~1.110301.0
    platformio/framework-arduinoteensy@~1.160.0
    platformio/tool-teensy@~1.159.0
