version: '3'

services:
  robot:
    image: universalrobots/ursim_e-series
    volumes:
      - ./externalcontrol:/urcaps/externalcontrol
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "29999:29999"
      - "30001-30004:30001-30004"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros:latest
    volumes:
      - ./server.py:/catkin_ws/src/server.py
    command: bash -c "source /opt/ros/rolling/setup.bash && python3 /catkin_ws/src/server.py"
    depends_on:
      - robot
    develop:
      watch:
        - action: sync
        - path: .
        - target: /catkin_ws/src
  
  sensor1:
    build:
      context: .
      dockerfile: Dockerfile_sensor1
    image: ros:latest
    volumes:
      - ./sensor1.py:/catkin_ws/src/sensor1.py
    command: bash -c "source /opt/ros/rolling/setup.bash && python3 /catkin_ws/src/sensor1.py"
    depends_on:
      - server


networks:
  default:
    driver: ursim
