name: tabletop

services:
  devcontainer:
    build:
      context: .
    volumes:
      - $HOME/ws/src/tabletop:/root/ws/src/tabletop
    hostname: devcontainer
    networks:
      net:
        ipv4_address: 192.168.13.101
    environment:
      - DISPLAY=novnc:0.0

networks:
  net:
    attachable: true
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.13.0/24