name: tabletop

services:
  devcontainer:
    extends:
      file: ../compose.yaml
      service: server_base
    privileged: true
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    hostname: devcontainer
    environment:
      - DISPLAY=$DISPLAY
    command: bash -c
      "git config --global --add safe.directory /root/ws/src/tabletop
      && git config --global --add safe.directory /root/ws/src/moveit2
      && sleep infinity"

networks:
  tabletop_net:
    name: tabletop_net
    attachable: true
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
