name: tabletop

services:
  devcontainer:
    build:
      context: .
      pull: true
    volumes:
      - ../../..:/root/ws
      - ./starship.toml:/root/.config/starship.toml
    devices:
      - /dev/ttyACM0
    hostname: devcontainer
    networks:
      tabletop_net:
        ipv4_address: 192.168.12.101

networks:
  tabletop_net:
    name: tabletop_net
    attachable: true
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
