preprocess:
  filename: preprocessed.csv
  eyelink_freq: 1000
  markers_freq: 120
  eyelink_filter_window: 0.005
  markers_filter_window: null
  max_marker_gap: 0.05
data:
  test_size: 0.2
  val_folds: 5
  shuffle_test_split: false
  shuffle_val_split: false
  train_batch_size: 1024
  val_batch_size: 4096
  test_batch_size: 4096
model:
  class_name: GazeEstimationModelMLP
  input_size: 4
  hidden_sizes: [64, 128, 64]
  output_size: 3
  dropout_rate: 0.2
optimizer:
  class_name: AdamW
  lr: 0.001
criterion:
  class_name: MSELoss
  reduction: mean
train:
  num_epochs: 100
  patience_epochs: 10
weights_path: saved_weights/model.pt
predictions:
  filename: predictions.csv
visualize:
  eyelink_range:
    min_x: -30000
    max_x: 30000
    min_y: -30000
    max_y: 30000
  markers_range:
    min_x: 0.0
    max_x: 1.0
    min_y: -0.5
    max_y: 0.5
    min_z: 0.0
    max_z: 1.0
