/commander:
  ros__parameters:
    default_service_wait_timeout: 5.0
    default_service_call_timeout: 2.0

    max_plan_attempts: 5
    max_execution_attempts: 3
    max_reset_attempts: 3
    plan_and_execute_timeout: 20

    dashboard:
      installation: default.installation
      program: external_control.urp
      connect_timeout: 5.0

    planning:
      group_name: ur_manipulator
      pose_link: eef
      pipeline: ["ompl_rrt_star", "ompl_rrtc"]

    planning_scene:
      static_meshes:
        path: $(find-pkg-share tabletop_moveit_config)/meshes/static/rig.dae
        scale: 1.0
        simplification: bounding_primitive
        correction:
          position: [0.0, 0.0, -0.02]
          rpy: [0.0, 0.0, 1.5707]
      dynamic_meshes:
        path: $(find-pkg-share tabletop_moveit_config)/meshes/dynamic_dae/
        scale: 0.001
        simplification: convex_hull
        poses: # In meters
          complex_object:
            position: [-0.1, 0.4, 0.8]
          simple_object:
            position: [0.1, 0.3, 0.8]

    waypoints:
      path:
        - object_area
        - object_grab
        - object_area
        - monkey_area_1
        - monkey_area_2
        - object_area
        - object_grab
        - object_area
      poses_stamped:
        init:
          header:
            frame_id: world
          pose:
            position:
              x: 0.1
              y: 0.1
              z: 0.8
            rpy:
              roll: 0.0
              pitch: 0.0
              yaw: 1.5707

        object_area:
          header:
            frame_id: world
          pose:
            position:
              x: 0.3
              y: 0.6
              z: 0.6
            rpy:
              roll: 0.0
              pitch: 0.0
              yaw: 1.5707

        object_grab:
          header:
            frame_id: world
          pose:
            position:
              x: 0.3
              y: 0.65
              z: 0.6
            rpy:
              roll: 0.0
              pitch: 0.0
              yaw: 1.5707

        monkey_area_1:
          header:
            frame_id: world
          pose:
            position:
              x: -0.2
              y: -0.5
              z: 0.8
            rpy:
              roll: 0.4
              pitch: -0.1
              yaw: -1.5707

        monkey_area_2:
          header:
            frame_id: world
          pose:
            position:
              x: 0.2
              y: -0.5
              z: 0.7
            rpy:
              roll: -0.4
              pitch: 0.1
              yaw: -1.5707
