# Example config for the commander node
plan_and_execute_timeout: null

object_ids:
  - simple_object_5
  - simple_object_6
  - simple_object_7
  - simple_object_8
  - simple_object_9
  - simple_object_15
  - simple_object_16
  - simple_object_17
  - simple_object_18
  - simple_object_19
  - simple_object_25
  - simple_object_26
  - simple_object_27
  - simple_object_28
  - simple_object_29

goals:
  path:
    - monkey_area_1
    - monkey_area_2

  poses:
    monkey_area_1:
      position: [-0.2, -0.5, 0.9]
      rpy: [0.4, -0.1, -1.5707]

    monkey_area_2:
      position: [0.2, -0.5, 0.9]
      rpy: [-0.4, 0.1, -1.5707]
