"""Small operator-facing utilities for manipulation preflight reports."""

import argparse
import os
from pathlib import Path
from typing import Any

import yaml

from tabletop_rig.manipulation_preflight_report import (
    format_report_summary,
)

DEFAULT_REPORT_NAME = "manipulation_preflight.yaml"


def _repository_root() -> Path:
    configured = os.environ.get("TABLETOP_DIR")
    if configured:
        return Path(configured)
    return Path(__file__).resolve().parents[5]


def _cache_dir() -> Path:
    return Path(
        os.environ.get(
            "TABLETOP_CACHE_DIR", _repository_root() / ".cache" / "tabletop"
        )
    )


def _load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(
            f"No preflight report exists at {path}. "
            "Run 'tt-preflight run' first."
        )
    with path.open() as stream:
        value = yaml.safe_load(stream) or {}
    if not isinstance(value, dict):
        raise ValueError(f"Expected a YAML mapping in {path}")
    return value


def show_results(report_name: str = DEFAULT_REPORT_NAME) -> None:
    report_path = _cache_dir() / report_name
    report = _load_yaml(report_path)
    print(format_report_summary(report))
    print(f"\nFull report: {report_path}")


def _replace_once(text: str, old: str, new: str, description: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(
            f"Expected exactly one {description} in foraging_ordered.yaml; "
            f"found {count}"
        )
    return text.replace(old, new, 1)


def _finite_trial_count(
    task_config: dict[str, Any], report: dict[str, Any]
) -> int:
    generator = task_config["tasks"][0]["kwargs"]["trial_generator"]["kwargs"]
    grouped_ids = generator["grouped_object_ids"]
    available = {
        object_id
        for object_id, result in report.get("objects", {}).items()
        if result.get("status") == "PASS"
    }
    left_count = sum(
        object_id in available for object_id in grouped_ids["left_manipulator"]
    )
    right_count = sum(
        object_id in available
        for object_id in grouped_ids["right_manipulator"]
    )
    if left_count == 0 or right_count == 0:
        raise ValueError(
            "Preflight must contain at least one PASS object for each arm"
        )
    # OrderedChoiceAlternating starts on the left: N trials contain ceil(N/2)
    # left choices and floor(N/2) right choices.
    return max(2 * left_count - 1, 2 * right_count)


def prepare_real(report_name: str = DEFAULT_REPORT_NAME) -> None:
    root = _repository_root()
    cache_dir = _cache_dir()
    cache_dir.mkdir(parents=True, exist_ok=True)
    report = _load_yaml(cache_dir / report_name)
    if report.get("mode") != "mock_planning_only":
        raise ValueError("The report was not generated by mock planning")

    source_path = (
        root / "src/ros/tabletop/tabletop_tasks/config/foraging_ordered.yaml"
    )
    source = source_path.read_text()
    parsed_source = yaml.safe_load(source)
    finite_trials = _finite_trial_count(parsed_source, report)

    real = source
    real_once = _replace_once(
        real,
        "          num_trials: 100000\n",
        f"          num_trials: {finite_trials}\n",
        "'num_trials: 100000' setting",
    )
    real_smoke = _replace_once(
        real,
        "          num_trials: 100000\n",
        "          num_trials: 2\n",
        "'num_trials: 100000' setting",
    )

    outputs = {
        "two-trial smoke test": cache_dir / "foraging_real_smoke.yaml",
        "all-accessible finite test": cache_dir / "foraging_real_once.yaml",
        "normal long-running task": cache_dir / "foraging_real.yaml",
    }
    outputs["two-trial smoke test"].write_text(real_smoke)
    outputs["all-accessible finite test"].write_text(real_once)
    outputs["normal long-running task"].write_text(real)

    print("Real-use configurations prepared from the current task and report:")
    for description, path in outputs.items():
        print(f"  {description}: {path}")
    print(f"\nFinite test length: {finite_trials} trials")
    print(
        "These files are ignored cache files. Real loading still validates "
        "the mock report fingerprints before any task can start."
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Inspect preflight results or prepare guarded real configs."
    )
    parser.add_argument("command", choices=("results", "prepare-real"))
    parser.add_argument("--report", default=DEFAULT_REPORT_NAME)
    args = parser.parse_args()
    if args.command == "results":
        show_results(args.report)
    else:
        prepare_real(args.report)


if __name__ == "__main__":
    main()
