[program:print_url]
command: bash -c "echo $'#####################\nVNC URL: http://localhost:8080/vnc.html?autoconnect=true\n#####################'; sleep 60"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true