!ObjectResetConfig
start_goal: !PoseStamped
  position: [1.65, 1.0, 0.7]
  rpy: [0.0, 1.5707, 0.0]
  frame_id: world
reset_request: !ConcatPlanRequest
  goals:
    - !PoseStamped
      position: [1.75, 1.0, 0.7]
      rpy: [0.0, 1.5707, 0.0]
      frame_id: world
    - !PoseStamped
      position: [1.65, 1.0, 0.7]
      rpy: [0.0, 1.5707, 0.0]
      frame_id: world
allowed_collision_ids:
  - drawer_station
