!ObjectResetConfig
start_goal: !PoseStamped
  position: [1.65, 1.0, 0.7]
  rpy: [0.0, 0.0, 0.0]
reset_request: !ConcatPlanRequest
  goals:
    - !PoseStamped
      position: [1.75, 1.0, 0.7]
      rpy: [0.0, 0.0, 0.0]
    - !PoseStamped
      position: [1.65, 1.0, 0.7]
      rpy: [0.0, 0.0, 0.0]
  acceleration_scaling_factor: 0.5
object_allowed_collision_ids:
  - drawer_station
additional_allowed_collisions:
  - [eef_sphere, drawer_station]
