!ObjectResetConfig
start_goal: !PoseStamped
  position: [0.15, 0.0, 0.074]
  rpy: [1.5707, 0.7853, -1.5707]
  frame_id: left_reset_station/spike
reset_request: !ConcatPlanRequest
  goals:
    # Rotate all the way CW to make sure we can rotate at least 360 CCW
    - !JointStateDict
      left_wrist_3_joint: 0.0

    # Move forward into drawer station
    - !PoseStamped
      position: [0.075, 0.0, 0.074]
      rpy: [1.5707, 0.7853, -1.5707]
      frame_id: left_reset_station/spike

    # 180 deg spin CCW, then 360 spin CW
    - !JointStateDeltaDict
      left_wrist_3_joint: -3.1415
    - !JointStateDeltaDict
      left_wrist_3_joint: 6.2831

    # Retract to start position (Cartesian, unchanged)
    - !PoseStamped
      position: [0.15, 0.0, 0.074]
      rpy: [1.5707, -2.3561, -1.5707]
      frame_id: left_reset_station/spike
  planning_pipeline: ptp
object_allowed_collision_ids:
  - left_reset_station
additional_allowed_collisions:
  - [left_eef_sphere, left_reset_station]
