joint_limits:
  left_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  left_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  left_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  left_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  left_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  left_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  right_shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  right_shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  right_elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  right_wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  right_wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
  right_wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 30.0
    has_jerk_limits: true
    max_jerk: 500.0
