planning_scene_monitor_options:
  name: planning_scene_monitor
  robot_description: robot_description
  joint_state_topic: joint_states
  attached_collision_object_topic: planning_scene_monitor
  publish_planning_scene_topic: publish_planning_scene
  monitored_planning_scene_topic: monitored_planning_scene
  wait_for_initial_state_timeout: 1000.0

planning_pipelines:
  pipeline_names:
    - ompl
    - pilz_industrial_motion_planner
    # - isaac_ros_cumotion
    # - chomp
    # - stomp

linear:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: LIN
    planning_time: 0.05
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

ptp:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: PTP
    planning_time: 0.1
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

prm_star:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: PersistentLazyPRMstar
    planning_time: 2.0
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

rrt_star:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: APSRRTstar
    planning_time: 0.5 # TODO
    # planning_time: 2.0
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

rrtc:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: APSRRTConnect
    planning_time: 0.5
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

rrtc_star:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: APSRRTConnectstar
    planning_time: 0.5
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

#
# ompl_aps_persistent:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: APSPersistent
#     planning_time: 3.0
#     max_velocity_scaling_factor: 1.0
#     max_acceleration_scaling_factor: 1.0
#
# ompl_rrt_star:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: RRTstar
#     planning_time: 0.5
#     max_velocity_scaling_factor: 1.0
#     max_acceleration_scaling_factor: 1.0
#
# ompl_persistent_lazy_prm_star:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: SemiPersistentLazyPRMstar
#     planning_time: 3.0
#     max_velocity_scaling_factor: 1.0
#
# ompl_persistent_lazy_prm:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: PersistentLazyPRM
#     planning_time: 3.0
#     max_velocity_scaling_factor: 1.0
#     max_acceleration_scaling_factor: 1.0
#
# pilz_ptp:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: pilz_industrial_motion_planner
#     planner_id: PTP
#     planning_time: 0.1
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5
# cumotion:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: isaac_ros_cumotion
#     planning_time: 0.5
#     max_velocity_scaling_factor: 1.0
#     max_acceleration_scaling_factor: 1.0

# plan_request_params:
#   planning_attempts: 10 # Number of attempts the planning pipeline tries to solve a given motion planning problem
#   planning_pipeline: ompl # Name of the pipeline that is being used
#   planner_id: PersistentPRMstar # Name of the specific planner to be used by the pipeline
#   planning_time: 0.5 # Time budget for the motion plan request. If the planning problem cannot be solved within this time, an empty solution with error code is returned
#   max_velocity_scaling_factor: 0.5
#   max_acceleration_scaling_factor: 0.5

# ompl_aps_not_persistent:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: APSNotPersistent
#     planning_time: 5.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# ompl_aps_persistent:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: APSPersistent
#     planning_time: 5.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# ompl_rrtc:
#   plan_request_params:
#     planning_attempts: 8
#     planning_pipeline: ompl
#     planner_id: RRTConnect
#     planning_time: 0.5
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# ompl_rrt_star:
#   plan_request_params:
#     planning_attempts: 8
#     planning_pipeline: ompl
#     planner_id: RRTstar
#     planning_time: 1.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# ompl_prm_star:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: PersistentPRMstar
#     planning_time: 1.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# ompl_loading_prm:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: ompl
#     planner_id: PersistentLoadingPRM
#     planning_time: 1.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# chomp_planner:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: chomp
#     planning_time: 1.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5

# stomp_planner:
#   plan_request_params:
#     planning_attempts: 1
#     planning_pipeline: stomp
#     planning_time: 1.0
#     max_velocity_scaling_factor: 0.5
#     max_acceleration_scaling_factor: 0.5
