planning_scene_monitor_options:
  name: planning_scene_monitor
  robot_description: robot_description
  joint_state_topic: joint_states
  attached_collision_object_topic: planning_scene_monitor
  publish_planning_scene_topic: publish_planning_scene
  monitored_planning_scene_topic: monitored_planning_scene
  wait_for_initial_state_timeout: 1000.0

planning_pipelines:
  pipeline_names:
    - ompl
    - pilz_industrial_motion_planner

linear:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: LIN
    planning_time: 0.05
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

ptp:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: PTP
    planning_time: 0.1
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

rrt_star:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: RRTstar
    planning_time: 0.25
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

aps_rrt_star:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: APSRRTstar
    planning_time: 0.25
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

aps_rrtc:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: APSRRTConnect
    planning_time: 0.25
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0

aps_rrtc_star:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: ompl
    planner_id: APSRRTConnectstar
    planning_time: 0.25
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0
